parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\EventService:
        arguments:
            $apiUrl: '%env(resolve:API_URL)%'

    App\Service\UserRankService:
        arguments:
            $apiUrl: '%env(resolve:API_URL)%'

    App\Service\AchievementService:
        arguments:
            $apiUrl: '%env(resolve:API_URL)%'

    App\Service\BadgeService:
        arguments:
            $apiUrl: '%env(resolve:API_URL)%'

    App\Service\PostService:
        arguments:
            $apiUrl: '%env(resolve:BOMBEROS_API_URL)%'

    App\Service\NotificationService:
        arguments:
            $apiUrl: '%env(resolve:POLICIA_API_URL)%'
