<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNNXSGp9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNNXSGp9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNNXSGp9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNNXSGp9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNNXSGp9\App_KernelDevDebugContainer([
    'container.build_hash' => 'NNXSGp9',
    'container.build_id' => 'dc5b982d',
    'container.build_time' => 1678645379,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNNXSGp9');
