<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKFFjzi5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKFFjzi5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKFFjzi5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKFFjzi5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKFFjzi5\App_KernelDevDebugContainer([
    'container.build_hash' => 'KFFjzi5',
    'container.build_id' => 'b907b7d9',
    'container.build_time' => 1678646706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKFFjzi5');
